language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
- npm run build
deploy:
  - provider: firebase
    token:
      secure: IRggHK6aoMoO5SC+xqjjz1qaSUnhQulhaXV2u+zFJOidFh/KcG4AfuACQINidWa+5q7Rxwq+roBz08sozgOmNQ6wgleLIHIj7D7nIgz351QbvY2o+0LM/Gjd0nC3gVK1I6H3Hy8ikFlH2K1UYSrbq9KL4r4TWVAWLUG4fbPw4ZNaqtEpIA6cCx+PZKClxB+CUq/EPbNpB4s/YCWnNbG1yfJvYcxZajYAG4W1urLAjGPpx52hlwUB6mXldSOWZLpya7QalbYdG5Ofi0VWMqeo6/g1IYWJPtqZ+Dz6f8LG/KYUSb39n7VamePC/HoYPI6gSBe2P2rDV+83qoXZMCZ+HTmaIz6PXVXvHUZWYfbKzrc85XsqevJJ4pjKvWl5c9fej+oS5sBu/U6lGJWwY6AR80IakfCOeSQ3X2l77JqvUi7z9LdwPZmj25cSDH7xrllAFO+joCKDqm/t0u3g3XEPNKEbOMZrYVBooXGt6liDAZ53Y7P0DqbTnsuR5BW6JGkVhgXtNlKC4+ljojvy5FoS/N4CKrhWmBCJVMYO5P6p4t0MaYVjOLh+Qov5dABrxvV1XxLE5YPiNLfN9SusMiMuFFe1P1GNpAP6y3uQfe7uZnnD1wp3tadM3JvNLuX96cCcvc8t8rmOBtH8dAumSW0D9a8bB9O+9JSp7BLL4Zz7jnY=
    project: dev-tutka-meteo-fi
    skip_cleanup: true
    on:
      branch: devel
  - provider: firebase
    token:
      secure: IRggHK6aoMoO5SC+xqjjz1qaSUnhQulhaXV2u+zFJOidFh/KcG4AfuACQINidWa+5q7Rxwq+roBz08sozgOmNQ6wgleLIHIj7D7nIgz351QbvY2o+0LM/Gjd0nC3gVK1I6H3Hy8ikFlH2K1UYSrbq9KL4r4TWVAWLUG4fbPw4ZNaqtEpIA6cCx+PZKClxB+CUq/EPbNpB4s/YCWnNbG1yfJvYcxZajYAG4W1urLAjGPpx52hlwUB6mXldSOWZLpya7QalbYdG5Ofi0VWMqeo6/g1IYWJPtqZ+Dz6f8LG/KYUSb39n7VamePC/HoYPI6gSBe2P2rDV+83qoXZMCZ+HTmaIz6PXVXvHUZWYfbKzrc85XsqevJJ4pjKvWl5c9fej+oS5sBu/U6lGJWwY6AR80IakfCOeSQ3X2l77JqvUi7z9LdwPZmj25cSDH7xrllAFO+joCKDqm/t0u3g3XEPNKEbOMZrYVBooXGt6liDAZ53Y7P0DqbTnsuR5BW6JGkVhgXtNlKC4+ljojvy5FoS/N4CKrhWmBCJVMYO5P6p4t0MaYVjOLh+Qov5dABrxvV1XxLE5YPiNLfN9SusMiMuFFe1P1GNpAP6y3uQfe7uZnnD1wp3tadM3JvNLuX96cCcvc8t8rmOBtH8dAumSW0D9a8bB9O+9JSp7BLL4Zz7jnY=
    project: tutka-meteo-fi
    skip_cleanup: true
    on:
      branch: master
